# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2afc43a6ac15b10e64b48b0f8071d700e775d0f447f11ad4b1b004e4903c2e53fdf3a1ad31a21c0fbde328cb2957742ed30ffabae16727e08c170a0fee63bdf0

test:
  secret_key_base: 32abcfedb8ab8501a3dadfa6b37b6137f16fe9a830143dbe558c08e6f998f23f95de29b372b2540941df755503720d988cf8eb618b6f9a5b44a48bd65b9be40a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
